name: Deploy ke cPanel

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'   # otomatis update setiap 6 jam

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 195.88.211.130
          username: deploy@wartajanten.net
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: ./
          timeout: 60000
          state-name: ftp-deploy-${{ github.run_id }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
